version: "3"

services:
  web:
    image: trezonalecomte/pollen:0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE=host=db user=pollen
    ports:
      - "80:80"
    networks:
      - webnet

  db:
    image: postgres:9.6

networks:
  webnet:
