flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.2.2.0
- aeson-pretty-0.8.5
- aeson-qq-0.8.2
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.8.1
- appar-0.1.4
- attoparsec-0.13.2.0
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-compat-0.9.3
- base64-bytestring-1.0.0.1
- basement-0.0.2
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- cabal-doctest-1.0.2
- call-stack-0.1.0
- cmdargs-0.10.17
- conduit-1.2.12
- conduit-extra-1.1.17
- cookie-0.4.2.1
- cpphs-1.20.8
- cryptonite-0.24
- data-default-class-0.1.2.0
- dlist-0.8.0.3
- easy-file-0.2.1
- exceptions-0.8.3
- fast-logger-2.4.10
- file-embed-0.0.10.1
- foundation-0.0.15
- haskell-src-exts-1.19.1
- haskell-src-meta-0.8.0.1
- hex-0.1.2
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- hspec-wai-0.8.0
- hspec-wai-json-0.8.0
- http-api-data-0.3.7.1
- http-date-0.0.6.1
- http-media-0.7.1.1
- http-types-0.9.1
- http2-1.6.3
- integer-logarithms-1.0.2
- iproute-1.7.1
- lifted-base-0.2.3.11
- memory-0.14.8
- mime-types-0.1.0.7
- mmorph-1.1.0
- monad-control-1.0.2.2
- monad-logger-0.3.25.1
- monad-loops-0.4.3
- natural-transformation-0.4
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.14.0.0
- path-pieces-0.2.1
- persistent-2.7.0
- persistent-postgresql-2.6.1
- polyparse-1.12
- postgresql-libpq-0.9.3.1
- postgresql-simple-0.5.3.0
- psqueues-0.2.3.0
- quickcheck-io-0.2.0
- resource-pool-0.2.3.2
- resourcet-1.1.9
- safe-0.3.15
- scientific-0.3.5.2
- servant-0.11
- servant-server-0.11
- setenv-0.1.1.3
- silently-1.2.5
- simple-sendfile-0.2.25
- stm-chans-3.0.0.4
- streaming-commons-0.1.18
- string-conversions-0.4.0.1
- stringsearch-0.3.6.6
- system-filepath-0.4.13.4
- tagged-0.8.5
- th-abstraction-0.2.6.0
- th-expand-syns-0.4.3.0
- th-lift-0.7.7
- th-lift-instances-0.1.11
- th-orphans-0.13.4
- th-reify-many-0.1.8
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unix-time-0.3.7
- uri-bytestring-0.2.3.3
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vault-0.3.0.7
- void-0.7.2
- wai-3.2.1.1
- wai-app-static-3.1.6.1
- wai-extra-3.0.20.0
- wai-logger-2.3.0
- warp-3.2.13
- word8-0.1.3
resolver: ghc-8.0.1
