flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-0.11.3.0
- aeson-compat-0.3.7.1
- ansi-wl-pprint-0.6.8.1
- cryptonite-0.24
- file-embed-0.0.10.1
- haskell-src-exts-1.19.1
- optparse-applicative-0.14.0.0
- servant-0.9.1.1
- servant-server-0.9.1.1
- streaming-commons-0.1.18
resolver: lts-9.5
